# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: sky

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Website of Xiangling Xu 许湘灵, a PhD student at Inria Paris-Saclay specializing in quantum information, operator algebras, and noncommutative polynomial optimization.'
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: 'zA7dItn8ZqZZqmcOeec-vCEOBD0h-fdoVNuu3OE5MJk'
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    block: 'navbar'
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: 'Xiangling Xu 许湘灵'

# Site footer
footer:
  copyright:
    notice: '© {year} Me. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: '02/01/2006' # US: '01/02/2006' | UK: '02/01/2006'
  time_format: '15:04 MST'

# Site features
features:
  math:
    enable: true
    engine: mathjax
  privacy_pack:
    enable: false

# In config/_default/params.yaml

# publications:
#   # A list of author names to highlight in publications
#   highlight_authors:
#     - Xiangling Xu
#     - Xu, Xiangling
#     - X Xu
#     - X. Xu
#     - 许湘灵

# social:
#   - icon: envelope # at-symbol
#     # url: 'mailto:xu.xiangling@inria.fr'
#     label: xu[dot]xiangling[at]inria[dot]fr
#   #   label: E-mail Me
#   # - icon: brands/github
#   #   url: https://github.com/xiangling-xu
#   - icon: academicons/google-scholar
#     url: https://scholar.google.com/citations?user=cI2Q634AAAAJ&hl=en
#     label: Google Scholar
#   - icon: academicons/arxiv
#     url: https://arxiv.org/search/?query=Xu%2C+Xiangling&searchtype=author&abstracts=show&order=-announced_date_first&size=50
#     label: arXiv
#   - icon: academicons/orcid
#     url: https://orcid.org/0009-0009-9213-3049
#     label: ORCID