name: Deploy website to GitHub Pages

env:
  WC_HUGO_VERSION: '0.148.2'
  NODE_VERSION: '20'

on:
  push:
    branches: ['main']
  workflow_dispatch:

# We’re pushing to another repo branch, not using the Pages OIDC flow
permissions:
  contents: write

concurrency:
  group: deploy-pages
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm (if used)
        if: hashFiles('pnpm-lock.yaml') != ''
        uses: pnpm/action-setup@v4

      - name: Install dependencies (Tailwind etc.)
        run: |
          if [ -f "pnpm-lock.yaml" ]; then
            pnpm install
          elif [ -f "package.json" ]; then
            npm ci || npm install
          else
            echo "No package.json; skipping JS deps."
          fi

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ env.WC_HUGO_VERSION }}
          extended: true

      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
        run: hugo --minify

      - name: Inspect build output (debug)
        run: |
          echo "Built files:"
          du -sh public || true
          ls -la public | head -n 50 || true

      - name: Publish to host repo (SSH deploy key)
        uses: peaceiris/actions-gh-pages@v4
        with:
          external_repository: xiangling-xu/xiangling-xu.github.io
          publish_branch: main            # branch that GitHub Pages serves in the host repo
          publish_dir: ./public
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
          # force_orphan: true  # uncomment if the host repo branch has a messy history

      # --- OR, if you prefer a PAT instead of SSH, comment the block above and use this: ---
      # - name: Publish to host repo (Personal Access Token)
      #   uses: peaceiris/actions-gh-pages@v4
      #   with:
      #     external_repository: xiangling-xu/xiangling-xu.github.io
      #     publish_branch: main
      #     publish_dir: ./public
      #     personal_token: ${{ secrets.GH_PAT }}
      #     user_name: github-actions[bot]
      #     user_email: 41898282+github-actions[bot]@users.noreply.github.com
