name: Deploy website to GitHub Pages

env:
  WC_HUGO_VERSION: '0.148.2'
  NODE_VERSION: '20'

on:
  # Trigger the workflow every time you push to the `main` branch
  push:
    branches: ['main']
  # Allows you to run this workflow manually from the Actions tab on GitHub
  workflow_dispatch:

# Provide permission to clone the repo and deploy it to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  # Build and Deploy
  build-and-deploy:
    if: github.repository_owner != 'HugoBlox' # Safety check from theme
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Fetch history for Hugo's .GitInfo and .Lastmod
          fetch-depth: 0
          submodules: 'recursive' # Fetch the theme

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        if: hashFiles('package.json') != ''
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: |
          # Install Tailwind CLI if package.json exists
          if [ -f "package.json" ]; then
            echo "Installing Tailwind dependencies..."
            pnpm install || npm install
          fi

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ env.WC_HUGO_VERSION }}
          extended: true

      # Caching steps are kept for performance
      - uses: actions/cache@v4
        with:
          path: |
            /tmp/hugo_cache_runner/
            node_modules/
            modules/*/node_modules/
          key: ${{ runner.os }}-hugo-deps-${{ hashFiles('**/go.mod', '**/package-lock.json', '**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-hugo-deps-

      - uses: actions/cache@v4
        with:
          path: resources/
          key: ${{ runner.os }}-hugo-resources-${{ hashFiles('assets/**/*', 'config/**/*', 'hugo.yaml', 'package.json') }}
          restore-keys: |
            ${{ runner.os }}-hugo-resources-

      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
        # Build the site but do NOT set a baseURL. Hugo's config will handle it.
        run: hugo --minify

      - name: Generate Pagefind search index (if applicable)
        run: |
          # Check if site uses Pagefind search
          if [ -f "package.json" ] && grep -q "pagefind" package.json; then
            pnpm dlx pagefind --source "public" || npx pagefind --source "public"
          fi

      # --- This is the new deployment step ---
      - name: Deploy to your live site repo
        uses: peaceiris/actions-gh-pages@v4
        with:
          # The secret containing the private SSH key
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          # The repository to deploy to
          external_repository: JoeXuXXL/xiangling-xu.github.io # <-- CHANGE THIS
          # The branch to publish to. For user pages, it must be `main` or `master`.
          publish_branch: main
          # The folder in this repo that contains the built site
          publish_dir: ./public
          # A commit message for the deployment
          commit_message: ${{ github.event.head_commit.message }}
